name: Jeff
favicon: null
layout_spectrum: 0.33526666834950447
typography_spectrum: 0.6941613268572837
title: 'Jeff Harvey - photographer, creative, coffee lover'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
